###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = dolphin
$menu = wofi
$refresh_waybar = pkill waybar; waybar &
$refresh_wppr = pkill hyprpaper; hyprpaper &
$color_picker = hyprpicker



